services:
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --cleanup
  
  cf-tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - proxy

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
# Add Configurations for GPU Hardware Rendering Here:
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /docker-data/plex:/config
      - nfs-media:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VERSION=latest
    ports:
      - "32400:32400"
    networks:
      - proxy

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    volumes:
      - /docker-data/radarr:/config
      - nfs-media:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.calzone.zone`)"
      - "traefik.http.routers.radarr.entrypoints=https"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    networks:
      - proxy

  radarr-4k:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr-4k
    restart: unless-stopped
    volumes:
      - /docker-data/radarr-4k:/config
      - nfs-media:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr-4k.rule=Host(`radarr-4k.calzone.zone`)"
      - "traefik.http.routers.radarr-4k.entrypoints=https"
      - "traefik.http.routers.radarr-4k.tls=true"
      - "traefik.http.services.radarr-4k.loadbalancer.server.port=7878"
    networks:
      - proxy

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    volumes:
      - /docker-data/sonarr:/config
      - nfs-media:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.calzone.zone`)"
      - "traefik.http.routers.sonarr.entrypoints=https"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
    networks:
      - proxy

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    volumes:
      - /docker-data/prowlarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.calzone.zone`)"
      - "traefik.http.routers.prowlarr.entrypoints=https"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
    networks:
      - proxy

  overseerr:
    image: fallenbagel/jellyseerr:preview-seerr
    container_name: overseerr
    restart: unless-stopped
    volumes:
      - /docker-data/overseerr:/app/config
    environment:
      - TZ=America/Chicago
      - LOG_LEVEL=debug
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.rule=Host(`requests.calzone.zone`)"
      - "traefik.http.routers.overseerr.entrypoints=https"
      - "traefik.http.routers.overseerr.tls=true"
      - "traefik.http.services.overseerr.loadbalancer.server.port=5055"
    networks:
      - proxy

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    restart: unless-stopped
    volumes:
      - /docker-data/recyclarr:/config
    environment:
      - TZ=America/Chicago
    networks:
      - proxy

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    volumes:
      - /docker-data/bazarr:/config
      - nfs-media:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.calzone.zone`)"
      - "traefik.http.routers.bazarr.entrypoints=https"
      - "traefik.http.routers.bazarr.tls=true"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
    networks:
      - proxy

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /docker-data/tautulli:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tautulli.rule=Host(`tautulli.calzone.zone`)"
      - "traefik.http.routers.tautulli.entrypoints=https"
      - "traefik.http.routers.tautulli.tls=true"
      - "traefik.http.services.tautulli.loadbalancer.server.port=8181"
    networks:
      - proxy

  maintainerr:
    image: ghcr.io/maintainerr/maintainerr:latest # or jorenn92/maintainerr:latest
    container_name: maintainerr
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - /docker-data/maintainerr:/opt/data
    environment:
      - TZ=America/Chicago
#      - BASE_PATH=/maintainerr # uncomment if you're serving maintainerr from a subdirectory
#      - UI_HOSTNAME=:: # uncomment if you want to listen on IPv6 instead (default 0.0.0.0)
#      - UI_PORT=6247 # uncomment to change the UI port (default 6246). Useful if you're on a network where the port is already in use
#      - API_PORT=3002 # uncomment to change the API port (default 3001). Useful if you're on a network where the port is already in use
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.maintainerr.rule=Host(`maintainerr.calzone.zone`)"
      - "traefik.http.routers.maintainerr.entrypoints=https"
      - "traefik.http.routers.maintainerr.tls=true"
      - "traefik.http.services.maintainerr.loadbalancer.server.port=6246"
    networks:
      - proxy

volumes:
  nfs-media:
    driver_opts:
      type: "nfs"
      o: "addr=truenas.calzone.zone,nolock,soft,nfsvers=4"
      device: ":/mnt/hdd-pool/media"

networks:
  proxy:
    external: true
