services:
  # watchtower:
  #   image: containrrr/watchtower
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   command: --interval 300
  
  cf-tunnel:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    command: tunnel --no-autoupdate run
    env_file: .env
    environment:
      - TUNNEL_TOKEN=${TUNNEL_TOKEN}
    networks:
      - proxy

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    restart: unless-stopped
# Add Configurations for GPU Hardware Rendering Here:
    devices:
      - /dev/dri:/dev/dri
    volumes:
      - /config/plex:/config
      - nfs-media:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - VERSION=latest
    ports:
      - "32400:32400"
    networks:
      - proxy

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    volumes:
      - /config/radarr:/config
      - nfs-media:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.rule=Host(`radarr.calzone.zone`)"
      - "traefik.http.routers.radarr.entrypoints=https"
      - "traefik.http.routers.radarr.tls=true"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"
    networks:
      - proxy

  radarr-4k:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr-4k
    restart: unless-stopped
    volumes:
      - /config/radarr-4k:/config
      - nfs-media:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr-4k.rule=Host(`radarr-4k.calzone.zone`)"
      - "traefik.http.routers.radarr-4k.entrypoints=https"
      - "traefik.http.routers.radarr-4k.tls=true"
      - "traefik.http.services.radarr-4k.loadbalancer.server.port=7878"
    networks:
      - proxy

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    restart: unless-stopped
    volumes:
      - /config/sonarr:/config
      - nfs-media:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.calzone.zone`)"
      - "traefik.http.routers.sonarr.entrypoints=https"
      - "traefik.http.routers.sonarr.tls=true"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"
    networks:
      - proxy

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    volumes:
      - /config/prowlarr:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.calzone.zone`)"
      - "traefik.http.routers.prowlarr.entrypoints=https"
      - "traefik.http.routers.prowlarr.tls=true"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
    networks:
      - proxy

  overseerr:
    image: ghcr.io/sct/overseerr:develop
    container_name: overseerr
    restart: unless-stopped
    volumes:
      - /config/overseerr:/app/config
    environment:
      - TZ=America/Chicago
      - LOG_LEVEL=debug
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.overseerr.rule=Host(`requests.calzone.zone`)"
      - "traefik.http.routers.overseerr.entrypoints=https"
      - "traefik.http.routers.overseerr.tls=true"
      - "traefik.http.services.overseerr.loadbalancer.server.port=5055"
    networks:
      - proxy

  recyclarr:
    image: ghcr.io/recyclarr/recyclarr
    container_name: recyclarr
    restart: unless-stopped
    volumes:
      - /config/recyclarr:/config
    environment:
      - TZ=America/Chicago
    networks:
      - proxy

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    restart: unless-stopped
    volumes:
      - /config/bazarr:/config
      - nfs-media:/media
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.bazarr.rule=Host(`bazarr.calzone.zone`)"
      - "traefik.http.routers.bazarr.entrypoints=https"
      - "traefik.http.routers.bazarr.tls=true"
      - "traefik.http.services.bazarr.loadbalancer.server.port=6767"
    networks:
      - proxy

  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
    volumes:
      - /config/tautulli:/config
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tautulli.rule=Host(`tautulli.calzone.zone`)"
      - "traefik.http.routers.tautulli.entrypoints=https"
      - "traefik.http.routers.tautulli.tls=true"
      - "traefik.http.services.tautulli.loadbalancer.server.port=8181"
    networks:
      - proxy

volumes:
  nfs-media:
    driver_opts:
      type: "nfs"
      o: "addr=truenas.calzone.zone,nolock,soft,nfsvers=4"
      device: ":/mnt/hdd-pool/media"

networks:
  proxy:
    external: true
