services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v2.2.0
    restart: unless-stopped
    env_file: .env
    volumes:
      - /docker-data/pocket-id:/app/data
    # Optional healthcheck
    healthcheck:
      test: [ "CMD", "/app/pocket-id", "healthcheck" ]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pocket-id.rule=Host(`auth.calzone.zone`)"
      - "traefik.http.routers.pocket-id.entrypoints=https"
      - "traefik.http.routers.pocket-id.tls=true"
      - "traefik.http.services.pocket-id.loadbalancer.server.port=1411"
    networks:
      - proxy