SUPERUSER_EMAIL=op://docker/netbox/SUPERUSER_EMAIL
SUPERUSER_PASSWORD=op://docker/netbox/SUPERUSER_PASSWORD
POSTGRES_PASSWORD=op://docker/netbox/POSTGRES_PASSWORD
DB_PASSWORD=op://docker/netbox/POSTGRES_PASSWORD
