PAPERLESS_URL=op://docker/paperless/PAPERLESS_URL
PAPERLESS_SECRET_KEY=op://docker/paperless/PAPERLESS_SECRET_KEY
POSTGRES_PASSWORD=op://docker/paperless/POSTGRES_PASSWORD
PAPERLESS_DBPASS=op://docker/paperless/POSTGRES_PASSWORD
