POSTGRES_PASSWORD=op://docker/metamcp/POSTGRES_PASSWORD
BETTER_AUTH_SECRET=op://docker/metamcp/BETTER_AUTH_SECRET
OIDC_CLIENT_ID=op://docker/metamcp/OIDC_CLIENT_ID
OIDC_CLIENT_SECRET=op://docker/metamcp/OIDC_CLIENT_SECRET
BOOTSTRAP_USER_EMAIL=op://docker/metamcp/BOOTSTRAP_USER_EMAIL
BOOTSTRAP_USER_PASSWORD=op://docker/metamcp/BOOTSTRAP_USER_PASSWORD
NETBOX_TOKEN=op://docker/netbox-mcp/API_TOKEN
