services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:0.6.26-ls377
    container_name: calibre-web
    restart: unless-stopped
    volumes:
      - /docker-data/calibre-web:/config
      - nfs-media:/media
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
      - DOCKER_MODS=linuxserver/mods:universal-calibre  # enables ebook conversion
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.calibre-web.rule=Host(`books.calzone.zone`)"
      - "traefik.http.routers.calibre-web.entrypoints=https"
      - "traefik.http.routers.calibre-web.tls=true"
      # - "traefik.http.routers.calibre-web.middlewares=pocket-id-auth@file"
      - "traefik.http.services.calibre-web.loadbalancer.server.port=8083"
    networks:
      - proxy

volumes:
  nfs-media:
    driver_opts:
      type: "nfs"
      o: "addr=truenas.calzone.zone,nolock,soft,nfsvers=4"
      device: ":/mnt/hdd-pool/media"

networks:
  proxy:
    external: true
