services:
  shelfarr:
    image: ghcr.io/pedro-revez-silva/shelfarr@sha256:4d2b46adea8b6c1fc9ebdf63c48f91b8beb358c0688ab8d29e19726e370b147b
    container_name: shelfarr
    restart: unless-stopped
    volumes:
      - /docker-data/shelfarr/data:/rails/storage
      - nfs-media:/media
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
      - SOLID_QUEUE_IN_PUMA=1
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.shelfarr.rule=Host(`bookrequests.calzone.zone`)"
      - "traefik.http.routers.shelfarr.entrypoints=https"
      - "traefik.http.routers.shelfarr.tls=true"
      - "traefik.http.services.shelfarr.loadbalancer.server.port=80"
    networks:
      - proxy

volumes:
  nfs-media:
    driver_opts:
      type: "nfs"
      o: "addr=truenas.calzone.zone,nolock,soft,nfsvers=4"
      device: ":/mnt/hdd-pool/media"

networks:
  proxy:
    external: true
