services:
  minio:
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - nfs-minio:/data
    environment:
      - MINIO_ROOT_USER
      - MINIO_ROOT_PASSWORD
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      # S3 API
      - "traefik.http.routers.minio.rule=Host(`s3.calzone.zone`)"
      - "traefik.http.routers.minio.entrypoints=https"
      - "traefik.http.routers.minio.tls=true"
      - "traefik.http.routers.minio.service=minio"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"
      # Web console
      - "traefik.http.routers.minio-console.rule=Host(`minio.calzone.zone`)"
      - "traefik.http.routers.minio-console.entrypoints=https"
      - "traefik.http.routers.minio-console.tls=true"
      - "traefik.http.routers.minio-console.middlewares=pocket-id-auth@file"
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
    networks:
      - proxy

volumes:
  nfs-minio:
    driver_opts:
      type: "nfs"
      o: "addr=truenas.calzone.zone,nolock,soft,nfsvers=4"
      device: ":/mnt/hdd-pool/apps/minio"

networks:
  proxy:
    external: true
